project:
  type: website
 
website:
  title: "David Niño"
  favicon: "dimension.png"
  navbar:
    background: "#1A2E40"
    foreground: "#FDFEFE"
    logo: "dimension.png"
    logo-alt: "David Niño logo"
    right:
      - text: "Home"
        file: index.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "BioEpi Insights"
        file: bioepi.qmd
      - text: "Photos"
        file: photos.qmd
  page-footer:
    background: "#EDF3F8"
    foreground: "#223C53"
    border: false
    center:
      - icon: github
        href: https://github.com/
      - icon: google
        href: https://scholar.google.com/citations?user=igCiJo0AAAAJ&hl=es
      - icon: linkedin
        href: https://www.linkedin.com/in/davidninotorres/
    right: |
      This site is developed by David Niño-Torres using [Quarto](https://quarto.org/), an open-source scientific and technical publishing system.
    left: |
      Supported by [![](images/posit-logo.svg){fig-alt="Posit" width=65px}](https://posit.co/)
      
format:
  html:
    theme: morph
    css: styles.css
    mainfont: "Source Sans Pro"
    monofont: "Fira Code"
    fontsize: 1rem
    linkcolor: "#3D6B94"
    backgroundcolor: "#FFFFFF"
    toc: true
    toc-depth: 2
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
 
editor: visual


