project:
  type: website

website:
  title: "David Niño"
  # favicon: "dimension.png"
  navbar:
    background: "#1A2E40"
    foreground: "#FDFEFE"
    # logo: "dimension.png"
    logo-alt: "David Niño logo"
    search: true
    border: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "BioEpi Insights"
        file: bioepi.qmd
      - text: "Photos"
        file: photos.qmd
  page-footer:
    background: "#EDF3F8"
    foreground: "#223C53"
    border: true
    center:
      - icon: github
        href: https://github.com/
      - icon: google
        href: https://scholar.google.com/citations?user=igCiJo0AAAAJ&hl=es
      - icon: linkedin
        href: https://www.linkedin.com/in/davidninotorres/
    right: |
      <span> This site is developed by David Niño-Torres using {{< fa brands r-project >}} and [Quarto](https://quarto.org/), both open-source tools for scientific and technical publishing </span>
    left: |
      <span>
        Supported by <a href="https://posit.co/">
        <img src="images/posit-logo.svg" alt="Posit" height="16" style="vertical-align: middle;"/>
        </a>
      </span>

filters:
  - fontawesome

format:
  html:
    theme: morph
    css: styles.css
    mainfont: "Source Sans Pro"
    monofont: "Fira Code"
    fontsize: 1rem
    linkcolor: "#3D6B94"
    backgroundcolor: "#FFFFFF"
    toc: true
    toc-depth: 2
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual


