---
title: "Curriculum Vitae"
toc: true
toc-depth: 2
# title-block-banner: true
css: styles.css
---

> To us, probability is the very guide of life. —Marcus Tullius Cicero

## 🏛️ Education

**Pontificia Universidad Javeriana**, Bogotá D.C, Colombia\
**MSc in Biostatistics**, 2024 – 2026\
*Relevant coursework:* Longitudinal data analysis, Categorical data analysis, Advanced biostatistical methods, Epidemiology, and Health economics.\
*Thesis:* *Transitions in illicit drug use among youth: an analysis using a latent Markov model*\
*Supervisors:* Nelcy Rodríguez Malagón, Carlos Gómez Restrepo.

**Universidad Nacional de Colombia**, Bogotá D.C, Colombia\
**BSc in Statistics**, 2014 – 2021\
*Relevant coursework:* Spatial Statistics, Bayesian Statistics, Stochastic Processes, Regression analysis, Demography.\
*Thesis:* *Stochastic modelling of the COVID-19 pandemic with explicit behavioural changes in Bogotá: a case study*\
*Supervisors:* Liliana Blanco, Viswanathan Arunachalam.

## 🔬 Research experience

**Pontificia Universidad Javeriana, Faculty of Medicine**, Bogotá D.C, Colombia\
**Research Assistant: Statistician**, 2023 – Present\
*Department of Clinical Epidemiology and Biostatistics*

**NIHR Global Health Research Centre on Non-communicable Diseases and Mental Health in Latin America** [NIHR LATAM Centre](https://nihrlatamcentre.com)

- Performed sociodemographic and epidemiological analyses of specific departments in Colombia using national data sources (DANE and SISPRO) in R: Cleaned, integrated, and visualised data for research reports.
- Designed and delivered quantitative data analysis workshops in R for researchers.
- Contributed to the development of the statistical analysis plan and the design of REDCap databases for data collection in a cluster-randomized and site-stratified randomized trials.

**OLA Study: Mental Health among Youth in Latin America** [OLA Study](https://theolastudy.com)

- Managed the end-to-end analysis of baseline and cohort sociodemographic and psychosocial data, including data processing and cleaning, statistical modelling using generalized linear and longitudinal models, and the preparation of research reports and contributions to scientific manuscript writing.

**Universidad Nacional de Colombia, Faculty of Engineering**, Bogotá D.C, Colombia\
**Research Assistant: Statistician**, 2021 – 2023\
*LAB101 - Innovation, Creativity, and New Technologies Laboratory* [LAB101 UNAL](https://sites.google.com/view/lab101unal/inicio)

- Analysed and visualised data on internet service quality in collaboration with Colombia's Communications Regulation Commission (CRC)
- Designed indicators to assess the digital transformation process at Universidad Nacional de Colombia
- Provided consulting on data analysis, statistical modelling, and geospatial analysis for projects with Bogotá's city council
- Applied deep learning techniques for data automation and analysis


## 🏫 Academic experience

**Universidad Nacional de Colombia, Department of Statistics**, Bogotá D.C, Colombia\
**Student Assistant**, 2019 – 2022\
*Stochastic Processes Research Group*

- Processed and cleaned COVID-19 surveillance data
- Implemented Markov chains and stochastic differential equations to project the evolution of the pandemic in Bogotá

## 🧠 Skills and Interests

**Technical Skills:** R (advanced), Python (intermediate), SAS (basic), SQL (basic)\
**Languages:** Spanish (native), English (A2)\

## 📜 Certifications

**Epidemiology for Public Health Specialisation**, 2026\
*Imperial College London (Coursera)* — Credential ID: 5YZVOX9FCTSN

- Measuring Disease in Epidemiology, Study Designs in Epidemiology, and Validity and Bias in Epidemiology

**Infectious Disease Modelling Specialisation**, 2020\
*Imperial College London (Coursera)* - Credential ID: PQYP8CKJFYS3

- SIR model development, interventions, and calibration

**TensorFlow Developer Professional Certificate**, 2020\
*DeepLearning.AI (Coursera)* - Credential ID: MPC3F53UD7QX

- AI, machine learning, and deep learning using TensorFlow
- Convolutional Neural Networks, NLP, time series, and forecasting

```{=html}
<style>
h1, h2, h3 {
  font-weight: 600;
}
</style>
```
